language: ruby
sudo: false
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.3
  - 2.3.4
gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_1.gemfile
before_install: gem install bundler -v 1.15.0
script: bundle exec rake spec
services:
  - redis-server
