# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97d07133901efe2a08b7186ccb530e0b0418c54e1e29a4e32715f953a26f65fe4c38486b2ba76d4a24a867422a22475cc99bd5a53d7df59606eb241e65016686

test:
  secret_key_base: 542aa40c827448fcaea1e189e35c15533982b63c8cd6bd2f8d832637bb544504d258ce6ac688d1b9f38f11aeee4bcb965bdb201fb31681ea348bd48dd8e9c87f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
